/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e1e0ff",
        "surface-container-high": "#e7e8e9",
        "surface": "#f8f9fa",
        "on-tertiary-fixed-variant": "#6b3b00",
        "primary-container": "#2e3192",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#6ff7ee",
        "surface-bright": "#f8f9fa",
        "primary": "#15157d",
        "on-primary-fixed-variant": "#373a9b",
        "background": "#f8f9fa",
        "on-secondary-container": "#00716b",
        "surface-dim": "#d9dadb",
        "outline-variant": "#c7c5d4",
        "on-background": "#191c1d",
        "on-tertiary-fixed": "#2d1600",
        "secondary-fixed": "#6ff7ee",
        "on-secondary-fixed": "#00201e",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#00504c",
        "on-primary-container": "#9da1ff",
        "inverse-primary": "#c0c1ff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "error": "#ba1a1a",
        "surface-container-low": "#f3f4f5",
        "on-surface-variant": "#464652",
        "secondary": "#006a65",
        "on-tertiary-container": "#f5921c",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#5f3400",
        "surface-tint": "#4f54b4",
        "error-container": "#ffdad6",
        "outline": "#777683",
        "secondary-fixed-dim": "#4edbd2",
        "tertiary-fixed-dim": "#ffb875",
        "tertiary-fixed": "#ffdcc0",
        "surface-container-highest": "#e1e3e4",
        "surface-container": "#edeeef",
        "inverse-surface": "#2e3132",
        "on-primary-fixed": "#04006d",
        "on-primary": "#ffffff",
        "tertiary": "#402100"
      },
      spacing: {
        "xs": "8px",
        "xl": "64px",
        "margin-mobile": "20px",
        "lg": "40px",
        "base": "4px",
        "margin-desktop": "120px",
        "md": "24px",
        "sm": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "title-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
